#!/bin/sh
lockfile=`dirname $0`/ibmxt.lock
graph=vga
if [ ! -z "$1" ];then
    graph=$1
fi
if ( set -o noclobber; echo "$$" > "$lockfile") 2> /dev/null; then

        trap 'rm -f "$lockfile"; exit $?' INT TERM EXIT

        cd "`dirname $0`"
        pce-ibmpc -c `basename $0`.cfg -l `basename $0`-pce.log -g "$graph" -r

        # clean up after yourself, and release your trap
        rm -f "$lockfile"
        trap - INT TERM EXIT
else
        echo "Lock Exists: $lockfile owned by $(cat $lockfile)"
fi
