#!/usr/bin/env python3
"""
Generate extra/144feat.inc from symbol tables produced by cpm_asm86.
Extracts FEAT144_* symbols from both stock (ccp.sym, pcbios.sym, bdos.sym)
and experimental (ccpexp.sym, pcbioexp.sym, bdosexp.sym) builds.
"""

import sys
import re

def parse_sym_file(path):
    syms = {}
    with open(path, 'r', errors='ignore') as f:
        content = f.read()
    # Match hexadecimal address followed by symbol name, e.g. "0322 FEAT144CCPSTK1"
    for match in re.finditer(r'([0-9A-Fa-f]{4})\s+([A-Za-z0-9_]+)', content):
        addr_hex, name = match.groups()
        syms[name.upper()] = addr_hex.upper()
    return syms

def main():
    stock_ccp = parse_sym_file('ccp.sym')
    stock_bdos = parse_sym_file('bdos.sym')
    stock_bios = parse_sym_file('pcbios.sym')

    exp_ccp = parse_sym_file('ccpexp.sym')
    exp_bdos = parse_sym_file('bdosexp.sym')
    exp_bios = parse_sym_file('pcbioexp.sym')

    lines = [
        "; Auto-generated by tools/gen_144feat_inc.py - DO NOT EDIT MANUALLY",
        "; Contains patch site offsets extracted from kernel .sym files.",
        "",
        "; --- Stock Kernel (cpm.sys / cpmorg.sys) ---",
        f"KRNL_STOCK_CCPSTK1  EQU 0{stock_ccp.get('FEAT144CCPSTK1', '031F')}h",
        f"KRNL_STOCK_CCPSTK2  EQU 0{stock_ccp.get('FEAT144CCPSTK3', '035F')}h",
        f"KRNL_STOCK_CCPSTK3  EQU 0{stock_ccp.get('FEAT144CCPSTK3', '035F')}h",
        f"KRNL_STOCK_CCPSTK4  EQU 0{stock_ccp.get('FEAT144CCPSTK4', '07DB')}h",
        f"KRNL_STOCK_BDOSSTK  EQU 0{stock_bdos.get('FEAT144BDOSSTK', '0B31')}h",
        f"KRNL_STOCK_BIOSRESET EQU 0{stock_bios.get('FEAT144BIOSRESET', '2D18')}h",
        f"KRNL_STOCK_BIOSINTREG EQU 0{stock_bios.get('FEAT144BIOSINTREG', '2D4F')}h",
        f"KRNL_STOCK_BIOSSECTRN EQU 0{stock_bios.get('FEAT144BIOSSECTRN', '2BEB')}h",
        f"KRNL_STOCK_BIOSTRKBUF EQU 0{stock_bios.get('FEAT144BIOSTRKBUF', '2D95')}h",
        f"KRNL_STOCK_BIOSCBSTK  EQU 0{stock_bios.get('FEAT144BIOSCBSTK', '2EB7')}h",
        f"KRNL_STOCK_BIOSCOLDJMP EQU 0{stock_bios.get('FEAT144BIOSCOLDJMP', '3D15')}h",
        f"KRNL_STOCK_BIOSRAMDSK EQU 0{stock_bios.get('FEAT144BIOSRAMDISK', '3DF9')}h",
        f"KRNL_STOCK_BIOSFIDDRQ EQU 0{stock_bios.get('FEAT144BIOSFIDDREQ', '3E59')}h",
        f"KRNL_STOCK_BIOSFIDDMSG EQU 0{stock_bios.get('FEAT144BIOSFIDDMSG', '3E89')}h",
        "",
        "; --- Experimental Kernel (cpmexp.sys) ---",
        f"KRNL_EXP_CCPSTK1    EQU 0{exp_ccp.get('FEAT144CCPSTK1', '0322')}h",
        f"KRNL_EXP_CCPSTK2    EQU 0{exp_ccp.get('FEAT144CCPSTK3', '0362')}h",
        f"KRNL_EXP_CCPSTK3    EQU 0{exp_ccp.get('FEAT144CCPSTK3', '0362')}h",
        f"KRNL_EXP_CCPSTK4    EQU 0{exp_ccp.get('FEAT144CCPSTK4', '07B9')}h",
        f"KRNL_EXP_BDOSSTK    EQU 0{exp_bdos.get('FEAT144BDOSSTK', '0B31')}h",
        f"KRNL_EXP_BIOSRESET   EQU 0{exp_bios.get('FEAT144BIOSRESET', '2D18')}h",
        f"KRNL_EXP_BIOSINTREG  EQU 0{exp_bios.get('FEAT144BIOSINTREG', '2D4F')}h",
        f"KRNL_EXP_BIOSSECTRN  EQU 0{exp_bios.get('FEAT144BIOSSECTRN', '2BEB')}h",
        f"KRNL_EXP_BIOSTRKBUF  EQU 0{exp_bios.get('FEAT144BIOSTRKBUF', '2D95')}h",
        f"KRNL_EXP_BIOSCBSTK   EQU 0{exp_bios.get('FEAT144BIOSCBSTK', '2EB7')}h",
        f"KRNL_EXP_BIOSCOLDJMP EQU 0{exp_bios.get('FEAT144BIOSCOLDJMP', '3D15')}h",
        f"KRNL_EXP_BIOSRAMDSK  EQU 0{exp_bios.get('FEAT144BIOSRAMDISK', '3DF9')}h",
        f"KRNL_EXP_BIOSFIDDRQ  EQU 0{exp_bios.get('FEAT144BIOSFIDDREQ', '3E59')}h",
        f"KRNL_EXP_BIOSFIDDMSG EQU 0{exp_bios.get('FEAT144BIOSFIDDMSG', '3E89')}h",
        ""
    ]

    out_file = sys.argv[1] if len(sys.argv) > 1 else 'extra/144feat.inc'
    with open(out_file, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Generated {out_file}")

if __name__ == '__main__':
    main()
